export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between px-24">
      <section id="hero" className="duration-1000 ">
        <div className=" w-screen min-h-screen flex-center">
          <div className="flex-center w-full">
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
            asdasdads <br />
          </div>
        </div>
      </section>
    </main>
  );
}
